name: ComChat
main: net.mcviral.dev.plugins.comchat.main.ComChat
version: 1.0
author: comdude2
loadbefore:
 - Essentials
commands:
   chat:
      description: This is this plugin's main command.
      usage: /<command> help
      permission: chat.use
      permission-message: You don't have the required permission to perform this command.
   mute:
      description: This is this plugin's main command.
      usage: /<command> help
      permission: chat.use
      permission-message: You don't have the required permission to perform this command.
   msg:
      description: This is this plugin's main messaging command.
      usage: /<command> help
      permission: chat.use
      permission-message: You don't have the required permission to perform this command.
   message:
      description: This is this plugin's main messaging command.
      usage: /<command> help
      permission: chat.use
      permission-message: You don't have the required permission to perform this command.
   m:
      description: This is this plugin's main messaging command.
      usage: /<command> help
      permission: chat.use
      permission-message: You don't have the required permission to perform this command.
   r:
      description: This is this plugin's main messaging command.
      usage: /<command> help
      permission: chat.use
      permission-message: You don't have the required permission to perform this command.
permissions:
    chat.*:
        description: Gives access to all chat commands.
        default: op
        children:
            chat.admin: true
            chat.moderate: true
            chat.spy: true
            chat.create: true
            chat.delete: true
            chat.colour: true
            chat.use: true
    chat.admin:
        description: Gives chat admin permissions.
        default: op
    chat.moderate:
        description: Gives chat moderator permissions.
        default: op
    chat.spy:
        description: Allows the player to view private messages.
        default: false
    chat.create:
        description: Allows the player to create chats (Channels).
        default: true
    chat.delete:
        description: Allows the player to delete chats (Channels).
        default: false
    chat.colour:
        description: Allows the player to use colour codes in their message.
        default: false
    chat.use:
        description: Allows usage of /chat
        default: true
